### PR TITLE
Updated setting Backend

### PR DESCRIPTION
**Pull request by keseven626**

### CODE REVIEW

**Comment by ColeDrain** [comment]
Please resolve the conflicts, and make sure you're up to date with the dev branch

**Review by ColeDrain — CHANGES_REQUESTED** [review]
Some of these changes clash with the dev branch, kindly resolve
Are you in anyway editing the frontend code too ?

**Comment by keseven626** [comment]
> Please resolve the conflicts, and make sure you're up to date with the dev branch
yes i change the frontend coz the guy did not write the function to submit each form

**Review by ColeDrain — COMMENTED** [review]
Hmm, did you forget to add something
Coz I can't see any new change, just a line added

**Pull request closed without merging**
